### ISSUE TITLE
Prevent fractional prices

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/Qwallet#101]
For trading it cannot have fractional value of QU

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/1a33b7cf-133d-45dc-a3b6-138d3697740d)

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/66e3f6df-64a3-4f0a-9f32-fc57b05be3e6)

**Comment by Gaussian120** [comment]
There is an error as you can see in the picture above.

**Comment by Qsilver97** [comment]
fixed
