### ISSUE TITLE
trading inputs need error checking

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/Qwallet#105]
for buy orders need to check enough QU
for sell orders need to check enough tokens
for cancel orders need to check existing orders exist that match the cancel order. eventually we can probably just remove the cancel buy and cancel sell when each open order gets a cancel button

**Comment by Gaussian120** [comment]
If you mention this issue 
It is causing confusion to users.

**Comment by Gaussian120** [comment]
1.for buy orders need to check enough QU

Currently unable to check.
I think a warning notice should be displayed.

**Comment by Gaussian120** [comment]
My thoughts on order cancellation:
I think you should put a special mark on your order and have a cancel button next to it.

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/9057b4d6-2134-4490-9aa2-5ae441e2a141)

**Comment by RealWorld777** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/165303709/cb388301-250f-4255-b941-12964c95e6bd)
i ve got this

**Comment by Qsilver97** [comment]
this is needed for both desktop and android

**Comment by Gaussian120** [comment]
but let me supplement my opinion.
Since cancellation takes about 3 minutes, I think there should be a sign indicating that it is currently being cancelled.

**Comment by Gaussian120** [comment]
In other words, users must be able to check whether they can cancel or not.
At first, I didn't know the progress, so I kept clicking the cancel button 10 times.

**Comment by Gaussian120** [comment]
The same applies when buying and selling for an order.
I would like to see a notification.

**Comment by Qsilver97** [comment]
for error checking, in addition to sufficient tokens, on token transfer it costs 1M QU
also no fractions for current tokens and QU
