### ISSUE TITLE
The chart scale is almost invisible.

### ISSUE THREAD

**Issue by Gaussian120** [Qsilver97/Qwallet#120]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/8962ba7c-9b2f-4fc1-b66c-d567b897288b)

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/89fc6f71-548b-4a3d-babf-32ffc5e77b7f)
I think this looks good

**Comment by Gaussian120** [comment]
https://github.com/RegionX-Labs/CorespaceWeigher-ui
this is chart source code.

**Comment by Qsilver97** [comment]
chart data is very sparse now, I think we need more full orderbooks and actual trades happening and then revisit the chart
it is a valid issue as the charts just seem wonky but I think until we have more data samples with changing values it is not making sense to optimize as once the charts are full of activity (see QU USD chart) it seems not so bad
