### ISSUE TITLE
Android trade history bug

### ISSUE THREAD

**Issue by Gaussian120** [Qsilver97/Qwallet#123]
There is one bug when receiving money from the other person.

When you receive the transfer, the total amount will be displayed accurately, but the transaction history will not display the last amount received.
However, transaction history displayed when i send money.
When I turn the wallet on and off, everything is displayed correctly.

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/a06b05c2-5806-49a6-8706-24539202dbaa)

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/bb953d62-1f74-4062-8c6f-0979d96ba11e)

**Comment by Gaussian120** [comment]
If i turn it off and re-login,
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/4cd20bb6-48dc-4e2f-a631-f8a9d5a8f815)

**Comment by RealWorld777** [comment]
fixed.
please check

**Comment by Gaussian120** [comment]
correct
resolved
wonderful
