### ISSUE TITLE
drop downs are redundant and should be able to be removed

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/Qwallet#129]
ACCOUNTS:
Top Drop-Down (Wallets) - can be removed and **works wrongly (anyway)**
-->I see all my Assets in the table below but if at top I select one then 0 Qwallet ... if I select the other then it shows up.

The way the new Accounts-overview is designed one could also remove the Asset-Drop down as everything is shown below!

https://discord.com/channels/768887649540243497/1219171011736375306/1243565508859662367

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/3a49427f-991b-4fb1-b2e5-3ccfe4117079)

**Comment by Gaussian120** [comment]
Why do we need a dropdown button?
