### ISSUE TITLE
( Desktop version )differences between the Linux and Windows versions.

### ISSUE THREAD

**Issue by Gaussian120** [Qsilver97/Qwallet#136]
As a result of testing the May 27th release, i found that there are differences between the Linux and Windows versions.
The difference is:
- this is Linux version
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/988e2511-96f4-4c74-a69b-04215c850894)

- this is Window version
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/fe35d9e3-20e5-4a42-b49a-da8ee8c309a9)

**Comment by Qsilver97** [comment]
same as 130
