### ISSUE TITLE
CFB token sending error

### ISSUE THREAD

**Issue by Gaussian120** [Qsilver97/Qwallet#211]
when sending CFB token,
A notification was displayed that the transfer was successful 
and it was registered in activities history, but the CFB token still remained.
why?
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/b36d53bf-309f-437c-9e2d-1ba5cb5433ee)

**Comment by Qsilver97** [comment]
this is a rare core bug that will be fixed next epoch. the 1M QU is taken but token not transferred.
