### ISSUE TITLE
POSTBETA: in trading tab, "cancel buy" click error 

### ISSUE THREAD

**Issue by Gaussian120** [Qsilver97/Qwallet#212]
If I enter a random amount  (CFB token) in the trading tab and click the "cancel buy" button, a new tick will be generated and the tick information will be displayed in the background.
But the problem is that this background does not disappear.
I have to turn off the app and turn it back on to make it go away.
If it is not my order, I would like it to display a warning message and not send a tick when I enter an random amount and click the "cancel buy" button.
I think it would work if you activate the “cancel buy” button only for “my bid”.

![image](https://github.com/Qsilver97/Qwallet/assets/153379385/a13a9634-a8e9-4189-8d8c-56a3dd09f174)
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/18f92857-a4e5-4265-abe5-adfbf56bdce9)

The most annoying problem is that the tick information indicator that appears in the background does not disappear.
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/fcf3d6ab-2251-43d5-9d2e-60e2ab300bff)

**Comment by Qsilver97** [comment]
Actually the solution for this is to remove the CancelBuy and CancelSell button
since we can specifically click the cancel button from the orderbook

**Comment by KastriotOrllati** [comment]
Opened a PR to remove Cancel Buy and Sell buttons here https://github.com/Qsilver97/Qwallet/pull/245

**Comment by Qsilver97** [comment]
After some discussions, we realized that the cancel buttons give a unique feature of being able to partially cancel existing orders. This is usually not available so we will keep this for now, v2 can reexamine this issue
