### ISSUE TITLE
activity listing not copyable

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/Qwallet#99]
when copying the address or txid from activity page, the full amount is not copied

**Comment by Qsilver97** [comment]
If there is enough space, might as well display complete txid and address

**Comment by Gaussian120** [comment]
Of course, the issues raised in issues 98 have been resolved.

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/dd1bad7c-7563-4370-8a7e-6984d4edac0c)

**Comment by Gaussian120** [comment]
![image](https://github.com/Qsilver97/Qwallet/assets/153379385/b99ab469-d840-47cc-948d-b7dad8e90e6a)

**Comment by Gaussian120** [comment]
Compare them with each other.
Think about which one is more convenient for users.
